<?php
// database/seeders/ProjectSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    public function run()
    {
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');
        }

        DB::table('projects')->truncate();

        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = ON');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }

        $projects = [
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Soudure Electronique - Trafic Light',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'EL ATTAR MAROUAN',
                'pole' => 'Pôle Industrie',
                'filiere' => 'GEOEAR',
                'groupe' => '201',
                'participants' => '[]',
                'dt_debut' => '2025-10-09',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-10-17',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'PIE',
                'intitule_projet' => 'PIE : Maquette Infermerie',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'Fatima Zohra boulesâad',
                'pole' => 'Pôle Santé',
                'filiere' => 'Ambulancier',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-10-10',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-10-10',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'PIE',
                'intitule_projet' => 'PIE : Maquette Espace de restauration',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'Jaouad Riahi',
                'pole' => 'Pôle Santé',
                'filiere' => 'Ambulancier',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-10-10',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-10-10',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'PIE',
                'intitule_projet' => 'PIE : Maquette Distribution de Café',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'Ikram El souini',
                'pole' => 'Pôle Santé',
                'filiere' => 'Radiologie diagnostique',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-10-10',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-10-10',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Granulateur à Lames rotatives modulaires et remplaçables localement',
                'statut' => 'Suspendu',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Salmane imounane',
                'pole' => 'Pôle AIG',
                'filiere' => 'Production graphique',
                'groupe' => '103',
                'participants' => '[]',
                'dt_debut' => '2025-10-14',
                'dt_fn_prevu' => null,
                'dt_suspension' => '2025-11-13',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'SortiBot',
                'statut' => 'Suspendu',
                'etape' => 'Étape 2 – Étude des besoins & Opportunités',
                'responsable_projet' => 'ANOUAR JBILOU',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie Industriel',
                'groupe' => 'GIOGM201',
                'participants' => '[]',
                'dt_debut' => '2025-10-14',
                'dt_fn_prevu' => null,
                'dt_suspension' => '2025-12-20',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Robot Parking',
                'statut' => 'Suspendu',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Moukhtar yedri hammou',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOESA201',
                'participants' => '[]',
                'dt_debut' => '2025-10-20',
                'dt_fn_prevu' => null,
                'dt_suspension' => '2025-11-03',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Système d\'arrosage goutte à goutte automatique - IrrigoSmart',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'Nafia Challak',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-10-30',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Logistic Autonome Robot - AutoLogix bot',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'HASBI MOHAMMED',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOEAR201',
                'participants' => '[]',
                'dt_debut' => '2025-10-30',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Soudure Electronique - Trafic Light',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'BOUAZIZ ABDERRAHMANE',
                'pole' => 'Pôle Industrie',
                'filiere' => 'GEOEAR',
                'groupe' => '201',
                'participants' => '[]',
                'dt_debut' => '2025-11-05',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-11-05',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Appareil de gestion d’absence des stagiaires - AbsTrack',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'Hassan ait talat',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-11-05',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Smart Baby diapers - DiapSense',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'Ilyas Taleuan',
                'pole' => 'Pôle Industrie',
                'filiere' => 'DEEA',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-11-11',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Système Aérien de First-Aid et Assistance Rurale Intégré',
                'statut' => 'Abandonné',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Ismail EL gharbouy',
                'pole' => 'Pôle DIA',
                'filiere' => 'Infrastructure Digitale',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-11-12',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => '2025-11-24',
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Essuie-glasse Mobile - MobiWipe',
                'statut' => 'Abandonné',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Salmane imounane',
                'pole' => 'Pôle AIG',
                'filiere' => 'Production graphique',
                'groupe' => '103',
                'participants' => '[]',
                'dt_debut' => '2025-11-13',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => '2025-12-19',
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'QR code MAP',
                'statut' => 'Suspendu',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Salmane imounane',
                'pole' => 'Pôle AIG',
                'filiere' => 'Production graphique',
                'groupe' => '103',
                'participants' => '[]',
                'dt_debut' => '2025-11-13',
                'dt_fn_prevu' => null,
                'dt_suspension' => '2025-11-13',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Contrôleur de Coupure Électrique - SmartPowerGuard',
                'statut' => 'Suspendu',
                'etape' => 'Étape 5 – Exigences & Cahier des charges',
                'responsable_projet' => 'Adnane Jemli',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-11-18',
                'dt_fn_prevu' => '2026-02-01',
                'dt_suspension' => '2026-02-27',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Casque intelligent de communication en environnement bruyant - Audix',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'BEN BELAID SOUKAINA',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOEAR201',
                'participants' => '[]',
                'dt_debut' => '2025-11-19',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Contrôleur consommation d\'électricité - EnerEye',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'Ben sghir mohamed',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '103',
                'participants' => '[]',
                'dt_debut' => '2025-11-21',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'PIE',
                'intitule_projet' => 'PIE : Maquette Bus',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => 'Smahan Hajji',
                'pole' => 'Pôle GC',
                'filiere' => 'Gestion des Entreprises',
                'groupe' => '104',
                'participants' => '[]',
                'dt_debut' => '2025-12-02',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2025-12-02',
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Poubelle de tri intelligent - iCleanTri',
                'statut' => 'Abandonné',
                'etape' => 'Étape 5 – Exigences & Cahier des charges',
                'responsable_projet' => 'Mohamed Elyazili',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-12-03',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => '2026-02-27',
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Industrie 4.0 pour réduction des déchets industriels',
                'statut' => 'Abandonné',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Youssef ben abdelkader',
                'pole' => 'Pôle Industrie',
                'filiere' => 'PQA',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2025-12-05',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => '2026-01-19',
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Nettoyage des façades vitrées des gratte-ciel : Sky Reg',
                'statut' => 'Suspendu',
                'etape' => 'Étape 5 – Exigences & Cahier des charges',
                'responsable_projet' => 'Salmane imounane',
                'pole' => 'Pôle AIG',
                'filiere' => 'Production graphique',
                'groupe' => '103',
                'participants' => '[]',
                'dt_debut' => '2025-12-15',
                'dt_fn_prevu' => '2026-02-01',
                'dt_suspension' => '2026-02-27',
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Module M211 - RC3 : Robot Collaboratif 3 axes',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'BOUAZIZ ABDERRAHMANE',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOEAR201',
                'participants' => '[]',
                'dt_debut' => '2026-01-20',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Module M211 - Projet de Synthése : Injecteur Plastique',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'NAFII HAITAM',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOEAR201',
                'participants' => '[]',
                'dt_debut' => '2026-01-20',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Module M211 - Recyclage Plastique pour chaine injection : RePlast',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => 'BENSAID ANAS',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOEAR201',
                'participants' => '[]',
                'dt_debut' => '2026-01-20',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Contrôle de la quantité de sérum Physiologique chez les patients - SERO-CARE',
                'statut' => 'En cours',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Abdelmounime El masslouhi',
                'pole' => 'Pôle Santé',
                'filiere' => 'IMB',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2026-01-22',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => null,
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Module projet EI - Ascenseur Automatique',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => '',
                'pole' => 'Pôle Industrie',
                'filiere' => 'EI',
                'groupe' => '201',
                'participants' => '[]',
                'dt_debut' => '2026-02-05',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Station automatisée intelligente de recyclage des eaux usée',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => '',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => 'GEOESA201',
                'participants' => '[]',
                'dt_debut' => '2026-02-12',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => '3i- Smart assistive communication glove',
                'statut' => 'En cours',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Bouzine Aicha',
                'pole' => 'Pôle Santé',
                'filiere' => 'IMB',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2026-02-18',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Puzzel éducatif',
                'statut' => 'En cours',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'El mouayad Rihab',
                'pole' => 'Pôle Santé',
                'filiere' => 'IMB',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2026-02-18',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'FABLAB',
                'intitule_projet' => 'Children Safty',
                'statut' => 'En cours',
                'etape' => 'Étape 1 – Cadrage de l’idée initiale',
                'responsable_projet' => 'Mohamed Eddouy',
                'pole' => 'Pôle Santé',
                'filiere' => 'IMB',
                'groupe' => '101',
                'participants' => '[]',
                'dt_debut' => '2026-02-18',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => 'Automate Programmable avec ESP x2',
                'statut' => 'En cours',
                'etape' => 'Étape 6 – Prototypage',
                'responsable_projet' => '',
                'pole' => 'Pôle Industrie',
                'filiere' => 'GEOESA EXC',
                'groupe' => '202',
                'participants' => '[]',
                'dt_debut' => '2026-02-19',
                'dt_fn_prevu' => '2026-04-01',
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => null,
                'remarques' => 'Nouveau',
            ],
            [
                'source_du_projet' => 'Pôle Industrie',
                'intitule_projet' => '4 projet de classe chargeur de battrie',
                'statut' => 'Terminé',
                'etape' => 'Cloture de projet',
                'responsable_projet' => '',
                'pole' => 'Pôle Industrie',
                'filiere' => 'Génie électrique',
                'groupe' => '101/102/103',
                'participants' => '[]',
                'dt_debut' => '2026-02-09',
                'dt_fn_prevu' => null,
                'dt_suspension' => null,
                'dt_abandon' => null,
                'dt_fn_reel' => '2026-02-17',
                'remarques' => null,
            ],
        ];

        foreach ($projects as $project) {
            unset($project['participants']);
            $project['created_at'] = now();
            $project['updated_at'] = now();
            DB::table('projects')->insert($project);
        }
    }
}